########## Keysight Technologies Added Changes To Satisfy LGPL 2.x Section 2(a) Requirements ##########
# Committed by: Marcian Lytwyn
# Commit ID: be394be5da5b4ebda7ddded3cd205c2f8196ea8c
# Date: 2017-06-13 16:50:37 +0000
--------------------
# Committed by: Marcian Lytwyn
# Commit ID: b9ad3f1efade0e9c5ee978b132f23e9ec6dc1dd7
# Date: 2017-06-12 23:25:01 +0000
--------------------
# Committed by: Marcian Lytwyn
# Commit ID: fbf1590ea2d3ef2ab1e7ced84637eb175a1cdc17
# Date: 2015-12-04 14:52:36 +0000
--------------------
# Committed by: Marcian Lytwyn
# Commit ID: 98048287ab6cdc89c589b9addd085e02827d30d2
# Date: 2015-08-08 14:46:58 +0000
--------------------
# Committed by: Marcian Lytwyn
# Commit ID: 54d9663829bd6c4925db775d367ffa5f2b6f4835
# Date: 2015-07-22 23:37:29 +0000
--------------------
# Committed by: Marcian Lytwyn
# Commit ID: bde51c9e0d9fadb23bf3f6a9bb3dec81b5006e03
# Date: 2015-07-22 23:22:45 +0000
--------------------
# Committed by: Marcian Lytwyn
# Commit ID: 1a3351607c14fc9b4c75155b68590480b49ce126
# Date: 2015-07-21 21:18:59 +0000
--------------------
# Committed by: Marcian Lytwyn
# Commit ID: 4480d228ecdb6e6e00e3092be0049ccaf7d5b156
# Date: 2015-07-21 21:10:07 +0000
--------------------
# Committed by: Marcian Lytwyn
# Commit ID: 366a02d09075c7d7cb99b6c6cdb28abca7b96006
# Date: 2015-06-20 22:37:23 +0000
--------------------
# Committed by: Marcian Lytwyn
# Commit ID: c6a5c9a81e2db87622cb6aabb593270345282c3e
# Date: 2015-06-11 17:48:41 +0000
--------------------
# Committed by: Marcian Lytwyn
# Commit ID: d58bab49fd214f5273467a648fceea8a2ece1b3f
# Date: 2015-05-07 23:48:36 +0000
--------------------
# Committed by: Marcian Lytwyn
# Commit ID: c008417ba08b5dbadd8307088d056289e07ea1a0
# Date: 2014-08-01 20:46:33 +0000
--------------------
# Committed by: Frank Le Grand
# Commit ID: 4b27157a46ce2a51d886db45ac5ccfec1b00c1d0
# Date: 2013-08-09 14:24:48 +0000
########## End of Keysight Technologies Notice ##########
#
#  Images makefile for GNUstep GUI Library
#  Copyright (C) 2009-2010 Free Software Foundation, Inc.
#
#  Author: Nicola Pero <nicola.pero@meta-innovation.com>
#  Date: September 2009
#
#  This file is part of the GNUstep GUI Library.
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 2 of the License, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with this library; see the file COPYING.LIB.
#  If not, see <http://www.gnu.org/licenses/> or write to the 
#  Free Software Foundation, 51 Franklin Street, Fifth Floor, 
#  Boston, MA 02110-1301, USA.

PACKAGE_NAME = gnustep-gui
GNUSTEP_LOCAL_ADDITIONAL_MAKEFILES=../gui.make
include $(GNUSTEP_MAKEFILES)/common.make

include ../Version

RESOURCE_SET_NAME = Images
Images_INSTALL_DIR = $(GNUSTEP_LIBRARY)/Images
Images_RESOURCE_FILES = \
 GNUstep.tiff \
 GNUstepMenuImage.tiff \
 GSSearch.tiff \
 GSStop.tiff \
 LogoGNUstep.tiff \
 MagnifyGlass.tiff \
 NSAddTemplate.tiff\
 NSActionTemplate.tiff\
 NSDropDownIndicatorTemplate.png\
 NSDropDownIndicatorTemplate-reversed.png\
 NSFontPanelActionButton.tiff\
 NSFontPanelActionButtonPressed.tiff\
 NSPathTemplate.tiff\
 NSComboArrow.tiff \
 NSRatingLevelIndicator.tiff \
 NSRemoveTemplate.tiff\
 NSStopProgressFreestandingTemplate.tiff\
 NSFolder.tiff\
 NSInfo.tiff\
 common_2DCheckMark.tiff \
 common_2DDash.tiff \
 common_3DArrowDown.tiff \
 common_3DArrowLeft.tiff \
 common_3DArrowRight.tiff \
 common_3DArrowRightH.tiff \
 common_3DArrowUp.tiff \
 common_ArrowDown.tiff \
 common_ArrowDownH.tiff \
 common_ArrowLeft.tiff \
 common_ArrowLeftH.tiff \
 common_ArrowRight.tiff \
 common_ArrowRightH.tiff \
 common_ArrowUp.tiff \
 common_ArrowUpH.tiff \
 common_CenterTabStop.tiff \
 common_Close.tiff \
 common_CloseBroken.tiff \
 common_CloseBrokenH.tiff \
 common_CloseH.tiff \
 common_ClosedHandCursor.tiff \
 common_ColorSwatch.tiff \
 common_ComboBoxEllipsis.tiff \
 common_DecimalTabStop.tiff \
 common_Desktop.tiff \
 common_Diamond.tiff \
 common_Dimple.tiff \
 common_DimpleHoriz.tiff \
 common_DocsFolder.tiff \
 common_DownloadFolder.tiff \
 common_DownArrowSmall.tiff \
 common_Folder.tiff \
 common_GSFolder.tiff \
 common_HelpCursor.tiff \
 common_HelpLink.tiff \
 common_Home.tiff \
 common_HomeDirectory.tiff \
 common_ImageFolder.tiff \
 common_Info.tiff\
 common_LeftTabStop.tiff \
 common_LibraryFolder.tiff \
 common_MiniWindowTile.tiff \
 common_Miniaturize.tiff \
 common_MiniaturizeH.tiff \
 common_MusicFolder.tiff \
 common_Mount.tiff \
 common_Nibble.tiff \
 common_OpenHandCursor.tiff \
 common_Printer.tiff \
 common_RadioOff.tiff \
 common_RadioOn.tiff \
 common_Right.tiff \
 common_RightH.tiff \
 common_RightTabStop.tiff \
 common_Root_Apple.tiff \
 common_Root_PC.tiff \
 common_Root_SGI.tiff \
 common_Root_Sparc.tiff \
 common_Root_Sparc2.tiff \
 common_SliderHoriz.tiff \
 common_SliderVert.tiff \
 common_StepperDown.tiff \
 common_StepperDownHighlighted.tiff \
 common_StepperUp.tiff \
 common_StepperUpHighlighted.tiff \
 common_SwitchOff.tiff \
 common_SwitchOn.tiff \
 common_TabDownSelectedLeft.tiff \
 common_TabDownSelectedRight.tiff \
 common_TabDownSelectedToUnSelectedJunction.tiff \
 common_TabDownUnSelectedJunction.tiff \
 common_TabDownUnSelectedLeft.tiff \
 common_TabDownUnSelectedRight.tiff \
 common_TabDownUnSelectedToSelectedJunction.tiff \
 common_TabSelectedLeft.tiff \
 common_TabSelectedRight.tiff \
 common_TabSelectedToUnSelectedJunction.tiff \
 common_TabUnSelectedToSelectedJunction.tiff \
 common_TabUnSelectedJunction.tiff \
 common_TabUnSelectedLeft.tiff \
 common_TabUnSelectedRight.tiff \
 common_Tile.tiff \
 common_ToolbarClippedItemsMark.tiff \
 common_ToolbarCustomizeToolbarItem.tiff \
 common_ToolbarSeparatorItem.tiff \
 common_ToolbarShowColorsItem.tiff \
 common_ToolbarShowFontsItem.tiff \
 common_ToolbarSpaceItem.tiff \
 common_Unknown.tiff \
 common_UnknownApplication.tiff \
 common_UnknownTool.tiff \
 common_Unmount.tiff \
 common_UpAndDownArrowSmall.tiff \
 common_copyCursor.tiff \
 common_linkCursor.tiff \
 common_noCursor.tiff \
 common_outlineCollapsed.tiff \
 common_outlineExpanded.tiff \
 common_outlineUnexpandable.tiff \
 common_ret.tiff \
 common_retH.tiff \
 common_ProgressIndeterminate_1.tiff \
 common_ProgressIndeterminate_2.tiff \
 common_ProgressIndeterminate_3.tiff \
 common_ProgressIndeterminate_4.tiff \
 common_ProgressIndeterminate_5.tiff \
 common_ProgressIndeterminate_6.tiff \
 common_ProgressSpinning_1.tiff \
 common_ProgressSpinning_2.tiff \
 common_ProgressSpinning_3.tiff \
 common_ProgressSpinning_4.tiff \
 common_ProgressSpinning_5.tiff \
 common_ProgressSpinning_6.tiff \
 common_ProgressSpinning_7.tiff \
 common_ProgressSpinning_8.tiff \
 common_ProgressSpinning2_1.png \
 common_ProgressSpinning2_2.png \
 common_ProgressSpinning2_3.png \
 common_ProgressSpinning2_4.png \
 common_ProgressSpinning2_5.png \
 common_ProgressSpinning2_6.png \
 common_ProgressSpinning2_7.png \
 common_ProgressSpinning2_8.png \
 common_ProgressSpinning2_9.png \
 common_ProgressSpinning2_10.png \
 common_ProgressSpinning2_11.png \
 common_ProgressSpinning2_12.png \
 nsmapping.strings \
 page_landscape.tiff \
 page_portrait.tiff

include $(GNUSTEP_MAKEFILES)/resource-set.make
